# .streamlit/config.toml

[theme]
# The base theme.
base = "dark"

# Primary accent color for widgets (buttons, sliders, etc.)
primaryColor = "#3CB371"  # Medium Sea Green

# Main background color
backgroundColor = "#0a2e1c"  # Very Dark Green (Forest Night)

# Background color for sidebar and other containers
secondaryBackgroundColor = "#1E4D2B" # Darker Sea Green

# Text color
textColor = "#FAFAFA" # Off-white

# Font style
font = "sans serif"
